import Head from 'next/head'
import { useRouter } from 'next/router';
import { v4 as uuidv4 } from 'uuid';

const Home = () => {
  const router = useRouter()
  const createRoom = () => {
    const roomId = uuidv4()
    router.push(`/room/${roomId}`)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={createRoom}>Create room</button>
      </main>
    </>
  )
}

export default Home
